// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMAHlvekhV1AaQMbObZ2x-PMxilwBSfA8',
    appId: '1:474449796021:web:b74ca21e347034429f17fc',
    messagingSenderId: '474449796021',
    projectId: 'todopushnotification-68229',
    authDomain: 'todopushnotification-68229.firebaseapp.com',
    storageBucket: 'todopushnotification-68229.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJDE9yK8DrM8Bhv6hpESqmAxBCbMpxWnI',
    appId: '1:474449796021:android:eae1de2136dff74b9f17fc',
    messagingSenderId: '474449796021',
    projectId: 'todopushnotification-68229',
    storageBucket: 'todopushnotification-68229.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl8ZHYm_xggzzUeKFMGSh9eJshT1SXJhw',
    appId: '1:474449796021:ios:9176c546b6baf28b9f17fc',
    messagingSenderId: '474449796021',
    projectId: 'todopushnotification-68229',
    storageBucket: 'todopushnotification-68229.firebasestorage.app',
    iosBundleId: 'com.example.publicForces',
  );
}
